In [1]:
import pandas as pd

In [2]:
df =  pd.read_csv("empsal_part_buck.csv")

In [3]:
df

   empid          empname          city    sal  age         dob         dept
0   E001       John Adams      New York  73400   29  1996-08-12      Finance
1   E002     Sarah Miller   Los Angeles  81200   34  1991-04-23           HR
2   E003    Michael Brown       Chicago  65400   41  1984-02-11  Engineering
3   E004      Emily Davis       Houston  58900   27  1998-06-04    Marketing
4   E005    Daniel Wilson       Phoenix  91300   45  1980-09-19           IT
..   ...              ...           ...    ...  ...         ...          ...
95  E096      Elise Hardy    Des Moines  58300   24  2001-05-30           HR
96  E097      Camden Bush       Modesto  72800   32  1993-04-03  Engineering
97  E098  Madeline Abbott  Fayetteville  75600   34  1991-01-28    Marketing
98  E099     Robert Drake    Shreveport  69100   30  1995-06-09      Finance
99  E100    Aurora Briggs         Akron  82300   38  1987-10-01           IT

[100 rows x 7 columns]

In [4]:
df.shape

(100, 7)

In [8]:
df.dtypes

empid      object
empname    object
city       object
sal         int64
age         int64
dob        object
dept       object
dtype: object

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   empid    100 non-null    object
 1   empname  100 non-null    object
 2   city     100 non-null    object
 3   sal      100 non-null    int64
 4   age      100 non-null    int64
 5   dob      100 non-null    object
 6   dept     100 non-null    object
dtypes: int64(2), object(5)
memory usage: 5.6+ KB

In [10]:
df

   empid          empname          city    sal  age         dob         dept
0   E001       John Adams      New York  73400   29  1996-08-12      Finance
1   E002     Sarah Miller   Los Angeles  81200   34  1991-04-23           HR
2   E003    Michael Brown       Chicago  65400   41  1984-02-11  Engineering
3   E004      Emily Davis       Houston  58900   27  1998-06-04    Marketing
4   E005    Daniel Wilson       Phoenix  91300   45  1980-09-19           IT
..   ...              ...           ...    ...  ...         ...          ...
95  E096      Elise Hardy    Des Moines  58300   24  2001-05-30           HR
96  E097      Camden Bush       Modesto  72800   32  1993-04-03  Engineering
97  E098  Madeline Abbott  Fayetteville  75600   34  1991-01-28    Marketing
98  E099     Robert Drake    Shreveport  69100   30  1995-06-09      Finance
99  E100    Aurora Briggs         Akron  82300   38  1987-10-01           IT

[100 rows x 7 columns]

In [11]:
df.columns

Index(['empid', 'empname', 'city', 'sal', 'age', 'dob', 'dept'], dtype='object')

In [12]:
df.index

RangeIndex(start=0, stop=100, step=1)

In [13]:
df

   empid          empname          city    sal  age         dob         dept
0   E001       John Adams      New York  73400   29  1996-08-12      Finance
1   E002     Sarah Miller   Los Angeles  81200   34  1991-04-23           HR
2   E003    Michael Brown       Chicago  65400   41  1984-02-11  Engineering
3   E004      Emily Davis       Houston  58900   27  1998-06-04    Marketing
4   E005    Daniel Wilson       Phoenix  91300   45  1980-09-19           IT
..   ...              ...           ...    ...  ...         ...          ...
95  E096      Elise Hardy    Des Moines  58300   24  2001-05-30           HR
96  E097      Camden Bush       Modesto  72800   32  1993-04-03  Engineering
97  E098  Madeline Abbott  Fayetteville  75600   34  1991-01-28    Marketing
98  E099     Robert Drake    Shreveport  69100   30  1995-06-09      Finance
99  E100    Aurora Briggs         Akron  82300   38  1987-10-01           IT

[100 rows x 7 columns]

In [21]:
type(df['empname'])

pandas.core.series.Series

In [18]:
df.get('dsfsdfsdf','no col present')

'no col present'

In [22]:
df.empname

0          John Adams
1        Sarah Miller
2       Michael Brown
3         Emily Davis
4       Daniel Wilson
           ...
95        Elise Hardy
96        Camden Bush
97    Madeline Abbott
98       Robert Drake
99      Aurora Briggs
Name: empname, Length: 100, dtype: object

In [23]:
df[['empname','age','city']]

            empname  age          city
0        John Adams   29      New York
1      Sarah Miller   34   Los Angeles
2     Michael Brown   41       Chicago
3       Emily Davis   27       Houston
4     Daniel Wilson   45       Phoenix
..              ...  ...           ...
95      Elise Hardy   24    Des Moines
96      Camden Bush   32       Modesto
97  Madeline Abbott   34  Fayetteville
98     Robert Drake   30    Shreveport
99    Aurora Briggs   38         Akron

[100 rows x 3 columns]

In [24]:
df.columns

Index(['empid', 'empname', 'city', 'sal', 'age', 'dob', 'dept'], dtype='object')

In [26]:
df[[col for col in df.columns if col.startswith('emp')]]

   empid          empname
0   E001       John Adams
1   E002     Sarah Miller
2   E003    Michael Brown
3   E004      Emily Davis
4   E005    Daniel Wilson
..   ...              ...
95  E096      Elise Hardy
96  E097      Camden Bush
97  E098  Madeline Abbott
98  E099     Robert Drake
99  E100    Aurora Briggs

[100 rows x 2 columns]

In [27]:
#rename col

In [32]:
df.rename({"city":"empcity"},axis=1,inplace=True)

In [31]:
df

   empid          empname          city    sal  age         dob         dept
0   E001       John Adams      New York  73400   29  1996-08-12      Finance
1   E002     Sarah Miller   Los Angeles  81200   34  1991-04-23           HR
2   E003    Michael Brown       Chicago  65400   41  1984-02-11  Engineering
3   E004      Emily Davis       Houston  58900   27  1998-06-04    Marketing
4   E005    Daniel Wilson       Phoenix  91300   45  1980-09-19           IT
..   ...              ...           ...    ...  ...         ...          ...
95  E096      Elise Hardy    Des Moines  58300   24  2001-05-30           HR
96  E097      Camden Bush       Modesto  72800   32  1993-04-03  Engineering
97  E098  Madeline Abbott  Fayetteville  75600   34  1991-01-28    Marketing
98  E099     Robert Drake    Shreveport  69100   30  1995-06-09      Finance
99  E100    Aurora Briggs         Akron  82300   38  1987-10-01           IT

[100 rows x 7 columns]

In [33]:
df

   empid          empname       empcity    sal  age         dob         dept
0   E001       John Adams      New York  73400   29  1996-08-12      Finance
1   E002     Sarah Miller   Los Angeles  81200   34  1991-04-23           HR
2   E003    Michael Brown       Chicago  65400   41  1984-02-11  Engineering
3   E004      Emily Davis       Houston  58900   27  1998-06-04    Marketing
4   E005    Daniel Wilson       Phoenix  91300   45  1980-09-19           IT
..   ...              ...           ...    ...  ...         ...          ...
95  E096      Elise Hardy    Des Moines  58300   24  2001-05-30           HR
96  E097      Camden Bush       Modesto  72800   32  1993-04-03  Engineering
97  E098  Madeline Abbott  Fayetteville  75600   34  1991-01-28    Marketing
98  E099     Robert Drake    Shreveport  69100   30  1995-06-09      Finance
99  E100    Aurora Briggs         Akron  82300   38  1987-10-01           IT

[100 rows x 7 columns]

In [34]:
df.rename({"sal":"empsal","age":"empage"},axis=1,inplace=True)

In [37]:
df

,empid,empname,empcity,empsal,empage,dob,dept
0,E001,John Adams,New York,73400,29,1996-08-12,Finance
1,E002,Sarah Miller,Los Angeles,81200,34,1991-04-23,HR
2,E003,Michael Brown,Chicago,65400,41,1984-02-11,Engineering
3,E004,Emily Davis,Houston,58900,27,1998-06-04,Marketing
4,E005,Daniel Wilson,Phoenix,91300,45,1980-09-19,IT
...,...,...,...,...,...,...,...
95,E096,Elise Hardy,Des Moines,58300,24,2001-05-30,HR
96,E097,Camden Bush,Modesto,72800,32,1993-04-03,Engineering
97,E098,Madeline Abbott,Fayetteville,75600,34,1991-01-28,Marketing
98,E099,Robert Drake,Shreveport,69100,30,1995-06-09,Finance
99,E100,Aurora Briggs,Akron,82300,38,1987-10-01,IT

In [39]:
df.columns = [col.upper() for col in df.columns]

In [40]:
df

,EMPID,EMPNAME,EMPCITY,EMPSAL,EMPAGE,DOB,DEPT
0,E001,John Adams,New York,73400,29,1996-08-12,Finance
1,E002,Sarah Miller,Los Angeles,81200,34,1991-04-23,HR
2,E003,Michael Brown,Chicago,65400,41,1984-02-11,Engineering
3,E004,Emily Davis,Houston,58900,27,1998-06-04,Marketing
4,E005,Daniel Wilson,Phoenix,91300,45,1980-09-19,IT
...,...,...,...,...,...,...,...
95,E096,Elise Hardy,Des Moines,58300,24,2001-05-30,HR
96,E097,Camden Bush,Modesto,72800,32,1993-04-03,Engineering
97,E098,Madeline Abbott,Fayetteville,75600,34,1991-01-28,Marketing
98,E099,Robert Drake,Shreveport,69100,30,1995-06-09,Finance
99,E100,Aurora Briggs,Akron,82300,38,1987-10-01,IT

In [41]:
df.columns = [col.lower() for col in df.columns]

In [46]:
df.columns = ['temp_{}'.format(col) for col in df.columns]

In [47]:
df

,temp_temp_empid_,temp_temp_empname_,temp_temp_empcity_,temp_temp_empsal_,temp_temp_empage_,temp_temp_dob_,temp_temp_dept_
0,E001,John Adams,New York,73400,29,1996-08-12,Finance
1,E002,Sarah Miller,Los Angeles,81200,34,1991-04-23,HR
2,E003,Michael Brown,Chicago,65400,41,1984-02-11,Engineering
3,E004,Emily Davis,Houston,58900,27,1998-06-04,Marketing
4,E005,Daniel Wilson,Phoenix,91300,45,1980-09-19,IT
...,...,...,...,...,...,...,...
95,E096,Elise Hardy,Des Moines,58300,24,2001-05-30,HR
96,E097,Camden Bush,Modesto,72800,32,1993-04-03,Engineering
97,E098,Madeline Abbott,Fayetteville,75600,34,1991-01-28,Marketing
98,E099,Robert Drake,Shreveport,69100,30,1995-06-09,Finance
99,E100,Aurora Briggs,Akron,82300,38,1987-10-01,IT

In [50]:
df.columns = [col.split('_')[-2] for col in df.columns]

In [52]:
df.rename({0:"zero"})

,empid,empname,empcity,empsal,empage,dob,dept
zero,E001,John Adams,New York,73400,29,1996-08-12,Finance
1,E002,Sarah Miller,Los Angeles,81200,34,1991-04-23,HR
2,E003,Michael Brown,Chicago,65400,41,1984-02-11,Engineering
3,E004,Emily Davis,Houston,58900,27,1998-06-04,Marketing
4,E005,Daniel Wilson,Phoenix,91300,45,1980-09-19,IT
...,...,...,...,...,...,...,...
95,E096,Elise Hardy,Des Moines,58300,24,2001-05-30,HR
96,E097,Camden Bush,Modesto,72800,32,1993-04-03,Engineering
97,E098,Madeline Abbott,Fayetteville,75600,34,1991-01-28,Marketing
98,E099,Robert Drake,Shreveport,69100,30,1995-06-09,Finance
99,E100,Aurora Briggs,Akron,82300,38,1987-10-01,IT

In [54]:
df["updated_on"]= '03.06.2026'

In [58]:
df1 = df.drop("dob",axis=1)

In [61]:
df.drop(columns=['empid','empname','empcity'])

    empsal  empage         dob         dept  updated_on
0    73400      29  1996-08-12      Finance  03.06.2026
1    81200      34  1991-04-23           HR  03.06.2026
2    65400      41  1984-02-11  Engineering  03.06.2026
3    58900      27  1998-06-04    Marketing  03.06.2026
4    91300      45  1980-09-19           IT  03.06.2026
..     ...     ...         ...          ...         ...
95   58300      24  2001-05-30           HR  03.06.2026
96   72800      32  1993-04-03  Engineering  03.06.2026
97   75600      34  1991-01-28    Marketing  03.06.2026
98   69100      30  1995-06-09      Finance  03.06.2026
99   82300      38  1987-10-01           IT  03.06.2026

[100 rows x 5 columns]

In [62]:
df.drop([0,2,5])

,empid,empname,empcity,empsal,empage,dob,dept,updated_on
1,E002,Sarah Miller,Los Angeles,81200,34,1991-04-23,HR,03.06.2026
3,E004,Emily Davis,Houston,58900,27,1998-06-04,Marketing,03.06.2026
4,E005,Daniel Wilson,Phoenix,91300,45,1980-09-19,IT,03.06.2026
6,E007,Matthew Lee,San Antonio,62300,26,1999-03-14,Engineering,03.06.2026
7,E008,Amanda Taylor,San Diego,84500,38,1987-05-22,Finance,03.06.2026
...,...,...,...,...,...,...,...,...
95,E096,Elise Hardy,Des Moines,58300,24,2001-05-30,HR,03.06.2026
96,E097,Camden Bush,Modesto,72800,32,1993-04-03,Engineering,03.06.2026
97,E098,Madeline Abbott,Fayetteville,75600,34,1991-01-28,Marketing,03.06.2026
98,E099,Robert Drake,Shreveport,69100,30,1995-06-09,Finance,03.06.2026
99,E100,Aurora Briggs,Akron,82300,38,1987-10-01,IT,03.06.2026

In [68]:
empdata = [[101,'Keshav','Pune'],
[102,'Amit','Mumbai'],
[101,'Tushar','Chennai'],
[102,'Amit','Mumbai']]

In [69]:
df3 = pd.DataFrame(empdata,columns=['id','name','city'])

In [70]:
df3

    id    name     city
0  101  Keshav     Pune
1  102    Amit   Mumbai
2  101  Tushar  Chennai
3  102    Amit   Mumbai

In [72]:
df3.drop_duplicates(inplace=True)

In [75]:
df3.loc[0,'city'] = 'mumbai'

In [77]:
df3.loc[0:1,"id":"city"]

    id    name    city
0  101  Keshav  mumbai
1  102    Amit  Mumbai

In [78]:
df3.loc[[0,2],["id","city"]]

    id     city
0  101   mumbai
2  101  Chennai

In [80]:
df3.loc[0:2,"name":"city"]

     name     city
0  Keshav   mumbai
1    Amit   Mumbai
2  Tushar  Chennai

In [ ]:
iloc -  intger based location

In [81]:
df3

    id    name     city
0  101  Keshav   mumbai
1  102    Amit   Mumbai
2  101  Tushar  Chennai

In [82]:
df = pd.read_html("COVID-19 pandemic by country and territory - Wikipedia.html")

In [85]:
df = df[12]

In [86]:
df

,Unnamed: 0,Country,Deaths / million,Deaths,Cases
0,NaN,World[a],894,7114238,779131743
1,NaN,Peru,6603,221071,4533808
2,NaN,Bulgaria,5681,38778,1341091
3,NaN,North Macedonia,5429,9991,352093
4,NaN,Bosnia and Herzegovina,5123,16419,404289
...,...,...,...,...,...
235,NaN,Pitcairn Islands,0,0,4
236,NaN,Tokelau,0,0,80
237,NaN,North Korea,0,0,0
238,NaN,Turkmenistan,0,0,0
239,^ Countries which do not report data for a col...,^ Countries which do not report data for a col...,^ Countries which do not report data for a col...,^ Countries which do not report data for a col...,^ Countries which do not report data for a col...

In [87]:
df.drop("Unnamed: 0",axis=1,inplace=True)

In [88]:
df

,Country,Deaths / million,Deaths,Cases
0,World[a],894,7114238,779131743
1,Peru,6603,221071,4533808
2,Bulgaria,5681,38778,1341091
3,North Macedonia,5429,9991,352093
4,Bosnia and Herzegovina,5123,16419,404289
...,...,...,...,...
235,Pitcairn Islands,0,0,4
236,Tokelau,0,0,80
237,North Korea,0,0,0
238,Turkmenistan,0,0,0
239,^ Countries which do not report data for a col...,^ Countries which do not report data for a col...,^ Countries which do not report data for a col...,^ Countries which do not report data for a col...

In [ ]:
df.loc